### ISSUE TITLE
Support for IE<11 had to be dropped?

### ISSUE THREAD

**Issue by kokujin** [sylvainpolletvillard/ObjectModel#18] opened 2016-04-04 09:00 UTC
@sylvainpolletvillard, would there still be a 1.2 version with stacked errors support? My code has been blocking on this feature for a few days now. Support for IE11 and up is not an option for me. Thanks

**Comment by sylvainpolletvillard** [comment] 2016-04-04 09:28
The decision to drop support for IE9-10 has not been easy. I know these browsers are still required for many projects.

I spent the last week trying to fix the compatibility issues on IE9 while everything was ready and functional for the other browsers. The main issue I have with IE<11 is the lack of support of __proto__ or Object.setPrototypeOf. In v1, it implies all kinds of hacks like Model.instanceOf or ensureProto. Also, the Object.setPrototypeOf sham was far from being spec-compliant. It had to mess up with the prototype chain and could have a negative impact on other libraries using Object.setPrototypeOf. I must confess I found these workarounds not acceptable to reach the level of quality and robustness I aim for this library. That's why the support *had to* be dropped. I hope you understand.

Now, considering your specific needs ; could you please elaborate on how this feature is blocking for you ? I understand that error stacking can help with debugging, but never considered this as an absolute necessity. I will continue to provide bug fixes on v1.x, but I can not promise I will add new features.

**Comment by kokujin** [comment] 2016-04-04 10:40
Thanks for the explanation. The reason why I was blocking was because I need it to display the corresponding errors in a dynamically generated UI. All errors would be reflected and displayed not just the first error.

**Comment by kokujin** [comment] 2016-04-04 10:42
Would the polyfill on MDN help? https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

**Comment by kokujin** [comment] 2016-04-04 10:46
hmm, my bad. It seems that the MDN polyfill is not that good

`````
// Only works in Chrome and FireFox, does not work in IE:
````

**Comment by kokujin** [comment] 2016-04-04 10:47
but this might interest you

https://gist.github.com/WebReflection/5593554

**Comment by sylvainpolletvillard** [comment] 2016-04-04 11:01
Thanks but I have already seen these links :) The first one is already used in ObjectModel: https://github.com/sylvainpolletvillard/ObjectModel/blob/master/src/helpers.js#L16

Unfortunately, both of these relies on \__proto__ which is not supported by IE<11. So in v1, I had to copy all the properties from the prototype, see : https://github.com/sylvainpolletvillard/ObjectModel/blob/d49199c4b233d7458b2b6115903e55256accd89f/src/helpers.js#L66

But by doing this, the prototype chain is broken. That's why we had the Model.instanceOf function in v1 : the instanceof operator could not work this way in IE<11.

**Comment by sylvainpolletvillard** [comment] 2016-04-04 11:03
I will try to mix up the v2 code related to error stacking in v1.1.5 and see how things are going.

**Comment by kokujin** [comment] 2016-04-04 11:05
That would be great

**Comment by sylvainpolletvillard** [comment] 2016-04-04 13:36
Good news ! I started over my previous work last week and I managed to get it working on IE9, with these evolutions :
- null is now a valid value for an optional property
- stack errors instead of throwing the first error catched
- added custom error collectors
- assert API has changed and now receives an optional description
- validate API has changed and now receives an optional error collector

You can see that most of changes in v2 are here, which means you should be able to use v2 documentation and have IE9 support.

However, the limitations explained previously are still here:
- you still have to use Model.instanceOf instead of instanceof operator
- Object.setPrototypeOf is overwritten with a non spec-compliant sham, which means it can behave in a bad way with other libraries using Object.setPrototypeOf
- some new internal functions in models, like validator and unstack, are exposed while they should be private.

I published this as v1.2, which should have been the initial version number before I decided to remove the IE-specific stuff.
Unit tests passed but I did not make intensive manual testing, so please give it a try : https://github.com/sylvainpolletvillard/ObjectModel/blob/master/dist/object-model-1.2.0.zip

**Comment by kokujin** [comment] 2016-04-04 14:08
You rock @sylvainpolletvillard  :)

**Comment by kokujin** [comment] 2016-04-04 14:11
Hmm, I have problems installing. The stacktrace:

`````
npm WARN install:inherits@2.0.1 ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/grunt-cli/node_modules/findup-sync/node_modules/glob/node_modules/inherits' -> '/usr/local/lib/node_modules/grunt-cli/node_modules/inherits'
````

**Comment by sylvainpolletvillard** [comment] 2016-04-04 14:56
I'm afraid this is a problem related to your configuration. I don't have any trouble with installing v1.2 dependencies, which are the same than v2. Try to remove your local node_modules folder and uninstall/reinstall grunt-cli globally.

**Comment by kokujin** [comment] 2016-04-04 15:02
Hmm, very strange, I cleared the npm cache and re-installed Gulp globally, same problem. Good news though, the 'errorCollector' works as expected, now I can assign errors to certain parts of the markup. :)

I think the error api would be much quicker to use if the errors were automatically assigned to an array attribute of Model named errors.

**Comment by sylvainpolletvillard** [comment] 2016-04-04 15:17
Like `myModelInstance.errors` ? This would not work for several reasons:
- you can't add properties to primitive models like  `Model(Number)`
- it would prevent having a property of your model definition named `errors`
- we would have to define when this property is reset, which is not a trivial choice
- the user would have to manually think about every place in his code where the model could change, to manually check for errors.

**Comment by kokujin** [comment] 2016-04-04 15:21
2 things which I noticed:

1.The version attribute in the package.json file is still pegged at 2.0.0
2. The postinstall script calls 'npm install -g grunt-cli' , which would fail on machines that need sudo to install global scripts. The install fails when it tries this and stops

Apart from that, it works. Thanks!

**Comment by sylvainpolletvillard** [comment] 2016-04-04 15:25
Are you sure you downloaded the right file ? The package.json file contained in object-model-1.2.0.zip has the `1.2.0` version as intended.
For `sudo`, see : http://stackoverflow.com/questions/16724259/npm-command-sudo-or-not

**Comment by kokujin** [comment] 2016-04-04 15:31
Oh, I forgot to clarify.

'npm install objectmodel --save' causes problems. The zip file I downloaded does'nt. That would mean you might have to build 2 releases(tags)

**Comment by sylvainpolletvillard** [comment] 2016-04-04 15:33
I did not publish 1.2 to npm yet. I do it right now, then you'll be able to install it with: `npm install objectmodel@1.2.0 --save`

**Comment by kokujin** [comment] 2016-04-04 15:40
Great! But check up on the postinstall attribute, it seems that it needs to be done differently with libraries that are installed globally, for example , http://stackoverflow.com/questions/13784600/how-to-deploy-node-app-that-uses-grunt-to-heroku

**Comment by sylvainpolletvillard** [comment] 2016-04-04 15:57
This stackoverflow question is about running grunt command on postinstall, not installing grunt-cli globally. You should be able to instal globally every NPM module without `sudo` by doing this : `$ sudo chown $(whoami) /usr/local/share/npm/bin`

**Comment by kokujin** [comment] 2016-04-04 16:04
ah well. I hope 1.2.0 installs cleanly. I have several modules that I install globally (Slush, Yeaoman, Ava e.t.c) I really  doubt if its my setup

**Comment by sylvainpolletvillard** [comment] 2016-04-04 16:25
If you have any other questions, we should discuss on [gitter](https://gitter.im/sylvainpolletvillard/ObjectModel?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) to not pollute this issue with unrelated subjects

**Comment by sylvainpolletvillard** [comment] 2016-04-05 20:47
I think I can close this issue. Feel free to open another one in case you got trouble with 1.2

**Closed by sylvainpolletvillard** 2016-04-05 20:47 UTC
