### ISSUE TITLE
Optional array model cause duplication in other instances of a model with default

### ISSUE THREAD

**Issue by BenjaminMINK** [sylvainpolletvillard/ObjectModel#130] opened 2020-08-28 11:00 UTC
Hello,

I've found a potential issue using an optionnal array model using `push` method when a default is set.

Accordling this script:

```javascript
const Person = ObjectModel({
  name: String,
  female: Boolean
})

const Mother = Person.extend({
  female: true,
  child: [Person]
})

const Father = Person.extend({
  female: false,
  child: [Person]
})

const Family = ObjectModel({
  father: Father,
  mother: Mother,
  children: [ArrayModel(Person)],
  grandparents: [ArrayModel([Mother, Father])]
}).defaultTo({
  children: []
})

const joe = new Person({ name: 'Joe', female: false })
const ann = new Person({ name: 'Ann', female: true })
const marie = new Person({ name: 'Marie', female: true })
const joanna = new Person({ name: 'Joanna', female: true })

const joefamily = new Family({
  father: joe,
  mother: ann
})

const joefamily2 = new Family({
  father: joe,
  mother: marie
})

joefamily.children.push(joanna)

console.log(joefamily, joefamily2)
```

The result is, both Family instances have the same children:

```
Model {
  children: [ Model { name: 'Joanna', female: true } ],
  father: Model { name: 'Joe', female: false },
  mother: Model { name: 'Ann', female: true }
}
Model {
  children: [ Model { name: 'Joanna', female: true } ],
  father: Model { name: 'Joe', female: false },
  mother: Model { name: 'Marie', female: true }
}
```

Is that expected cause of the default? Or have I misunderstand something?

A workaround to fix that is to reset to array the `children` property: `family.children = []` or to not use default on array models.

I'm not sure if other types do the same things...

**Comment by sylvainpolletvillard** [comment] 2020-08-28 11:43
Hello,

Yes that's a recurrent issue we tried to fix in several ways in the past, see https://github.com/sylvainpolletvillard/ObjectModel/issues/93 for context for example

The problem is that the intention of the developer is unclear whether the default value should be a common reference or not. Depending on the example, sometimes it makes sense and sometimes not.

In previous versions of ObjectModel, defaults were handled by using *prototypal inheritance*, so every instance of the model had the same reference to its default prop value defined in its prototype. The reference was common by purpose. But this pattern was found quite confusing for beginners with prototypes, so in v4 instead of using the prototype we do a deep merge of passed props with defaults. ie.

`new Family({ children })` → `this.children = deepmerge(children, model.default.children)`

It solves many confusions when using default nested object properties, yet there are still some cases not solved, and the empty array is a classic one. In your case, since no value is passed for `children`, there is nothing to merge so the default array is directly passed as value, and you get a common reference between model instances.

As you said, the workaround is to use a factory function to init your model:

`const createFamily = ({ father, mother, children = [] }) => new Family({ father, mother, children })`

since the default empty array is local to the function scope, each instance will have its own array.

Other libraries and frameworks that had to deal with this issue solve it by requiring you to always pass a function as argument, that return the default value. This is [the case for Vue](https://winnercrespo.com/why-does-the-data-property-on-a-vue-component-must-be-a-function/#:~:text=So%2C%20the%20reason%20why%20Vue,be%20reflected%20in%20all%20instances.) for example. I tried this syntax but did not find an elegant way to implement it. Not only it adds complexity on user side, but it's even more confusing when the default value you want to provide is a function itself.

**Comment by sylvainpolletvillard** [comment] 2020-08-28 11:54
Since the issue is recurrent even after v4 change, I'm willing to consider changing the behaviour again. Maybe detect arrays in default values and automatically clone them when assigning to the model ? 

If I'm doing this, I need to define a clear behaviour for all non-primitive objects. For example, does it makes sense to also clone Sets, Maps ? For objects that are not collections, it feels non appropriate ; a default HTMLElement or CanvasRenderingContext should not be cloned

**Comment by BenjaminMINK** [comment] 2020-10-01 16:07
Hello,

Sorry for the response time, and thank you for this detailed answer!

Unfortunately, I don't know if I can help you on the future choice on how to manager/rewrite this in this library like you've said in a previous comment, sorry..!

**Comment by sylvainpolletvillard** [comment] 2020-10-01 16:12
No problem. For now I will continue to remind the difference between defaults and initial values

**Closed by sylvainpolletvillard** 2020-10-01 16:12 UTC
