### ISSUE TITLE
npm install objectmodel failed

### ISSUE THREAD

**Issue by vbarbarosh** [sylvainpolletvillard/ObjectModel#23] opened 2016-08-25 20:29 UTC
$ npm install objectmodel
    npm http 304 https://registry.npmjs.org/abbrev
    npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/grunt-cli
    npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
    /usr/local/lib
    └── grunt-cli@1.2.0 

    npm ERR! Linux 3.16.0-4-amd64
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
    npm ERR! node v6.3.1
    npm ERR! npm  v3.10.3
    npm ERR! path /usr/local/lib/node_modules/grunt-cli
    npm ERR! code EACCES
    npm ERR! errno -13
    npm ERR! syscall access

    npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/grunt-cli'
    npm ERR!     at Error (native)
    npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/grunt-cli'
    npm ERR!     at Error (native)
    npm ERR!   errno: -13,
    npm ERR!   code: 'EACCES',
    npm ERR!   syscall: 'access',
    npm ERR!   path: '/usr/local/lib/node_modules/grunt-cli' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.
I think that the problem lies in ``grunt-cli`` dependency. Probably it should not be specified at all.

**Comment by sylvainpolletvillard** [comment] 2016-08-25 20:48
Hi, thanks for the report.

This is caused by the global flag `-g`. It appears you don't have the permission to install `grunt-cli` globally by default, but it can be installed locally. I removed the global flag recently (https://github.com/sylvainpolletvillard/ObjectModel/issues/22) but did bump version number yet to  release it on NPM yet. 

It should be fixed now with v2.1.1

**Closed** 2016-08-26 19:09 UTC
