### ISSUE TITLE
Null vs undefined

### ISSUE THREAD

**Issue by johncrenshaw** [sylvainpolletvillard/ObjectModel#13] opened 2016-03-16 00:57 UTC
parseDefinition interprets [Model] as [Model, undefined], which fails against null values. I can see the logic in this perhaps, but it was a surprise, and works very poorly on certain types of data (such as JSON consumed from APIs).

IMO parseDefinition should treat [Model] as [Model, null, undefined], since null is a popular variation of "not set", and the line between null and undefined is blurry at best.

Maybe it should be another option similar to the Model.conventionFor* options?

By default:
Model.conventionForNotSet = [undefined]

To be more flexible the developer would add this to their own code:
Model.conventionForNotSet = [null, undefined]

Thoughts?

**Comment by sylvainpolletvillard** [comment] 2016-03-16 09:37
It's an interesting question. In JavaScript we have undefined and null, which looks similar but serve different purposes. The reason I did not put null as a valid optional property value is that null is an assignment value: the programmer has to manually assign it to null, while JavaScript always use undefined. So when I worked on this, I was thinking, if the value is set to null _by design_, then maybe the developer should add it manually to the acceptable values.

But now you ask, I think I change my mind. I read this great article : http://ryanmorr.com/exploring-the-eternal-abyss-of-null-and-undefined/ , and now I believe it makes sense to interpret [Model] as [Model, undefined, null], because you may think of `null` as representing an expected absence of value

Not sure if this should be globally configurable. Explicitely passing [Model, undefined] or [Model, null] is probably good enough for specific use cases.

**Comment by sylvainpolletvillard** [comment] 2016-03-16 20:06
will be fixed in v1.2

**Comment by sylvainpolletvillard** [comment] 2016-04-03 23:20
fixed in v2.0 :+1:

**Closed by sylvainpolletvillard** 2016-04-03 23:20 UTC
